In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
indep=sc.fit_transform(indep)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
'max_features': [['sqrt', 'log2'], default := None],
'splitter':['best','random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
40 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
21 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'auto' (deprecated), 'sqrt', 'log2'} or None. Got ['sqrt', 'log2'] instead.

--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt', 'auto' (deprecated)} or None. Got ['sqrt', 'log2'] instead.

--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1247, in fit
    super().fit(
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 177, in fit
    self._validate_params()
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'auto' (deprecated), 'log2', 'sqrt'} or None. Got ['sqrt', 'log2'] instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.70278941 0.67486059        nan        nan
 0.70476098 0.67314493        nan        nan 0.70849198 0.70748167
        nan        nan 0.71752022 0.68381871]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': [['sqrt', 'log2'], None],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(indep)

# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(dep,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'poisson', 'max_features': None, 'splitter': 'best'}: 0.998667156135576

In [10]:
table=pd.DataFrame.from_dict(re)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003124,0.006249,0.000000,0.000000,squared_error,"[sqrt, log2]",best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.000000,0.000000,0.000000,0.000000,squared_error,"[sqrt, log2]",random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.003124,0.006249,0.003124,0.006249,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.735659,0.647909,0.736317,0.698143,0.695919,0.702789,0.032512,5
3,0.003125,0.006249,0.003125,0.006249,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.642958,0.620488,0.706944,0.691624,0.712289,0.674861,0.036566,7
4,0.000000,0.000000,0.000000,0.000000,friedman_mse,"[sqrt, log2]",best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
5,0.000000,0.000000,0.000000,0.000000,friedman_mse,"[sqrt, log2]",random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
6,0.009372,0.007653,0.000000,0.000000,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.735423,0.642531,0.728529,0.732095,0.685226,0.704761,0.036073,4
7,0.000000,0.000000,0.000000,0.000000,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.676531,0.577162,0.703168,0.749601,0.659262,0.673145,0.056857,8
8,0.000000,0.000000,0.000000,0.000000,absolute_error,"[sqrt, log2]",best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
9,0.000000,0.000000,0.000000,0.000000,absolute_error,"[sqrt, log2]",random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
10,0.028119,0.006249,0.003124,0.006249,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.728661,0.610388,0.712678,0.734902,0.755830,0.708492,0.050965,2
11,0.018745,0.006249,0.003124,0.006249,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.720098,0.653373,0.717515,0.748392,0.698031,0.707482,0.031466,3
12,0.000000,0.000000,0.000000,0.000000,poisson,"[sqrt, log2]",best,"{'criterion': 'poisson', 'max_features': ['sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
13,0.000000,0.000000,0.000000,0.000000,poisson,"[sqrt, log2]",random,"{'criterion': 'poisson', 'max_features': ['sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
14,0.000000,0.000000,0.003124,0.006249,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.734957,0.668764,0.757807,0.714627,0.711447,0.717520,0.029494,1
15,0.009373,0.007653,0.000000,0.000000,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.677819,0.622351,0.702230,0.643204,0.773489,0.683819,0.052618,6

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 23
BMI: 33
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [13]:
preinput=sc.transform([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
preinput

C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.1539595 ,  0.38330685,  0.75107928, -1.0105187 ,  1.97058663]])

In [14]:
Future_Prediction=grid.predict(preinput)

#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[36085.219]